cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/cats', to: 'cats#index', as: 'cats'
  # post '/cats', to: 'cats#create'
  # # post '/cats', to: 'cats#new'
  # get '/cats/new', to: 'cats#new'
  # get '/cats/:id', to: 'cats#show', as: 'cat'
  # patch '/cats', to: 'cats#edit'

  resources :cats
end

cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string
#  name        :string           not null
#  sex         :string(1)
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  validates :color, inclusion: { in: %w(white black orange grey pink), 
            message: "%(value) is not a valid color"}
  validates :sex, inclusion: { in: %w(M F),
            message: "%(value) is not a valid sex"}



  def age
    ((Date.today - self.birth_date)/365).to_i
  end


end

cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
    # render json: Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
    # render json: Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
    
    render :new    
  end

  # def edit
    
  # end

end

cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats/app/views/cats/index.html.erb
<h1>All Cats</h1>

<% @cats.each do |c|%>
<ul>
  <li><%= c.name%></li>
  <li><%= c.birth_date%></li>
  <li><%= c.age%></li>
  <li><%= c.color%></li>
  <li><%= c.sex%></li>
  <li><%= c.description%></li>
  <a href="<%= cat_url(c)%>">TAKE ME TO THE CAT!!!</a>
  <br>
</ul>
<% end %>

cats/app/views/cats/new.html.erb
<form action="<%= cats_url%>" method = "post">
  <label>Cat name:
    <input type="text" name="cats[name]" value=""/>
  </label>
  <label>Cat sex:
    <input type="radio" name="cats[sex]" value="M"/>Male <br>
    <input type="radio" name="cats[sex]" value="F"/>Female <br>
  </label>
  <label>Cat DOB:
    <input type="text" name="cats[name]" value=""/>
  </label>
  <label>Cat color:
    <select>
      <option value="black">BLACK</option>
      <option value="white">WHITE</option>
      <option value="orange">OrAnGe</option>
      <option value="grey">GrEy</option>
      <option value="pink">Pink</option>
    </select>
  </label>
  <label>Cat description:
    <input type="text" name="cats[name]" value=""/>
  </label>
  <input type="submit" value="BIG BUTTON!">
</form>

cats/app/views/cats/show.html.erb
<h1>Specific Cat</h1>
<ul>
  <li><%= @cat.name%></li>
  <li><%= @cat.birth_date%></li>
  <li><%= @cat.age%></li>
  <li><%= @cat.color%></li>
  <li><%= @cat.sex%></li>
  <li><%= @cat.description%></li>
  <a href="<%= cats_url %>">TAKE ME TO THE ALL THE CATS!!!</a>
  <br>
</ul>

cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- <%= javascript_include_tag 'application' %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>